### ISSUE TITLE
Query parameter and search field connection

### ISSUE THREAD

**Issue by enmust** [geocollections/eMaapou#138] opened 2021-03-02 11:09 UTC

**Comment by enmust** [comment] 2021-05-07 07:47
This also means that users should be able to share their search results

**Comment by enmust** [comment] 2021-05-17 06:32
This exists: https://nuxtjs.org/docs/2.x/components-glossary/pages-watchquery

**Comment by enmust** [comment] 2021-06-29 07:00
Add query prams only for quick search, other fields could be reviewed at later stage

**Comment by Erikdzo** [comment] 2022-10-27 10:28
duplicate of #843

**Closed by Erikdzo** 2022-10-27 10:28 UTC
Labels: enhancement
